### ISSUE TITLE
如何写docker命令？

### ISSUE THREAD

**Issue by luckypoem** [aricxu/docker_shadowsocks#1]
hi。

root@localhost:~# docker pull aricxu/shadowsocks
Using default tag: latest
latest: Pulling from aricxu/shadowsocks
aed15891ba52: Pull complete 
773ae8583d14: Pull complete 
d1d48771f782: Pull complete 
cd3d6cd6c0cf: Pull complete 
8ff6f8a9120c: Pull complete 
f6445691892a: Pull complete 
ea93742a3e82: Pull complete 
f2eaa1f78df8: Pull complete 
2e62d4a84915: Pull complete 
b9b72b12eba9: Pull complete 
f50ebd690411: Pull complete 
72293e216309: Pull complete 
3641f446cd88: Pull complete 
4eda0bf36aa2: Pull complete 
Digest: sha256:74eed24bfebe97375d3f59029d2996f4b4b61961edf435b7bec7add2a85679fd
Status: Downloaded newer image for aricxu/shadowsocks:latest
root@localhost:~# lsof -i:9488
root@localhost:~# docker run -d -p 9488:9388 aricxu/shadowsocks -p 9388 -k my_pw -m aes-256-cfb 
a8789f1f81597626a8a7b6a90e27fc5494ee3867c7dd7a2faac36602485a211c
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"-p\\\": executable file not found in $PATH\"\n".

遇到的错误怎么解决？难道我运行的docker命令不正确？
root@localhost:~#

**Comment by aricxu** [comment]
hi. 对于上个版本，需要按下面语句执行。
docker run -d -p 8123:8388 aricxu/shadowsocks  /usr/bin/ss-server -s 0.0.0.0 -p 8388  -k pwd -m aes-256-cfb
docker 错误的将 -p 认为是可执行程序。因为我没有指定 ENTRYPOINT，需要指明执行什么程序。

对于新版本的你的语句是对的
docker run -d -p 8123:8388 aricxu/shadowsocks  -s 0.0.0.0 -p 8388 -k pwd -m aes-256-cfb

**Comment by luckypoem** [comment]
我运行docker run -d -p 9488:9388 aricxu/shadowsocks  ss-server -p 9388 -k my_pw -m aes-256-cfb ，这次正常了。可用来翻墙。
不过我看了你的https://github.com/aricxu/docker_shadowsocks/blob/master/Dockerfile ，里面显示
pip install shadowsocks 而用pip install shadowsocks安装出来的可执行文件不是ssserver吗？怎么你上面却使用ss-server呢？

**Comment by aricxu** [comment]
我猜你本地的镜像是老的。pip 安装的是 ssserver 没错的。你可以看镜像大小，老的是 500+M，新的是 50+M
